/*
 * generated by Xtext 2.12.0
 */
package org.emoflon.ibex.handbook


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class SokobanExchangeFormatStandaloneSetup extends SokobanExchangeFormatStandaloneSetupGenerated {

	def static void doSetup() {
		new SokobanExchangeFormatStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
