/*
 * generated by Xtext 2.12.0
 */
package org.emoflon.ibex.handbook


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class SokobanExchangeFormatRuntimeModule extends AbstractSokobanExchangeFormatRuntimeModule {
}
